"""PDF Document Generator for Reports, Memory Summaries, and Chess Analysis."""

from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..core.logger import get_logger

logger = get_logger("documents.pdf")


class PDFReportGenerator:
    """Generates structured PDF documents and summary briefs."""

    def __init__(self, output_dir: str = "data/documents") -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_summary_pdf(
        self,
        title: str,
        content_sections: Dict[str, str],
        author: str = "LUMI AI Companion",
    ) -> str:
        """Create a clean PDF report and return the saved absolute filepath."""
        filename = f"lumi_report_{int(time.time())}.pdf"
        target_path = self.output_dir / filename

        # ReportLab or basic PDF binary stream builder
        try:
            from reportlab.lib.pagesizes import letter  # type: ignore
            from reportlab.pdfgen import canvas  # type: ignore

            c = canvas.Canvas(str(target_path), pagesize=letter)
            c.setFont("Helvetica-Bold", 18)
            c.drawString(50, 750, title)

            c.setFont("Helvetica-Oblique", 10)
            c.drawString(50, 730, f"Generated by {author} on {time.strftime('%Y-%m-%d %H:%M:%S')}")

            c.setLineWidth(1)
            c.line(50, 720, 550, 720)

            y = 690
            for sec_title, text in content_sections.items():
                if y < 100:
                    c.showPage()
                    y = 750

                c.setFont("Helvetica-Bold", 13)
                c.drawString(50, y, sec_title)
                y -= 20

                c.setFont("Helvetica", 10)
                # Word-wrap simulation
                for line in text.split("\n"):
                    c.drawString(60, y, line[:80])
                    y -= 15
                y -= 10

            c.save()
            logger.info(f"Generated PDF document saved to '{target_path}'.")
            return str(target_path)
        except (ImportError, Exception) as e:
            logger.warning(f"ReportLab not available ({e}). Creating plain-text summary fallback.")
            fallback_txt = target_path.with_suffix(".txt")
            with open(fallback_txt, "w", encoding="utf-8") as f:
                f.write(f"{title}\n{'='*len(title)}\n\n")
                for k, v in content_sections.items():
                    f.write(f"[{k}]\n{v}\n\n")
            return str(fallback_txt)
