ANIMALS = {
    # Felines
    'cat': {'template': 'feline', 'color': (255, 165, 0), 'audio': 'meow'},
    'tiger': {'template': 'feline', 'color': (255, 140, 0), 'stripes': True, 'audio': 'roar'},
    'lion': {'template': 'feline', 'color': (218, 165, 32), 'mane': True, 'audio': 'roar'},
    'leopard': {'template': 'feline', 'color': (255, 215, 0), 'spots': True, 'audio': 'roar'},
    'cheetah': {'template': 'feline', 'color': (255, 225, 0), 'spots': True, 'audio': 'meow'},
    'panther': {'template': 'feline', 'color': (30, 30, 30), 'audio': 'roar'},
    'jaguar': {'template': 'feline', 'color': (255, 200, 0), 'spots': True, 'audio': 'roar'},
    'cougar': {'template': 'feline', 'color': (200, 150, 100), 'audio': 'roar'},
    'lynx': {'template': 'feline', 'color': (210, 180, 140), 'audio': 'meow'},
    'puma': {'template': 'feline', 'color': (205, 133, 63), 'audio': 'roar'},
    
    # Canines
    'dog': {'template': 'canine', 'color': (150, 100, 50), 'audio': 'bark'},
    'wolf': {'template': 'canine', 'color': (120, 120, 130), 'audio': 'howl'},
    'fox': {'template': 'canine', 'color': (255, 100, 0), 'audio': 'squeak'},
    'coyote': {'template': 'canine', 'color': (180, 150, 120), 'audio': 'howl'},
    'jackal': {'template': 'canine', 'color': (160, 130, 90), 'audio': 'bark'},
    'hyena': {'template': 'canine', 'color': (130, 120, 90), 'audio': 'squeak'},
    'dingo': {'template': 'canine', 'color': (210, 150, 50), 'audio': 'bark'},
    'hound': {'template': 'canine', 'color': (100, 70, 40), 'audio': 'howl'},
    'husky': {'template': 'canine', 'color': (200, 200, 200), 'audio': 'howl'},
    'pug': {'template': 'canine', 'color': (220, 200, 180), 'audio': 'bark'},

    # Birds
    'bird': {'template': 'bird', 'color': (100, 200, 255), 'audio': 'chirp'},
    'parrot': {'template': 'bird', 'color': (50, 205, 50), 'audio': 'chirp'},
    'eagle': {'template': 'bird', 'color': (139, 69, 19), 'audio': 'eagle_cry'},
    'owl': {'template': 'bird', 'color': (160, 120, 90), 'audio': 'hoot'},
    'crow': {'template': 'bird', 'color': (40, 40, 40), 'audio': 'caw'},
    'pigeon': {'template': 'bird', 'color': (169, 169, 169), 'audio': 'coo'},
    'sparrow': {'template': 'bird', 'color': (180, 150, 120), 'audio': 'chirp'},
    'hawk': {'template': 'bird', 'color': (160, 100, 50), 'audio': 'eagle_cry'},
    'falcon': {'template': 'bird', 'color': (120, 120, 120), 'audio': 'eagle_cry'},
    'swan': {'template': 'bird', 'color': (255, 255, 255), 'audio': 'honk'},
    'duck': {'template': 'bird', 'color': (34, 139, 34), 'audio': 'quack'},
    'goose': {'template': 'bird', 'color': (220, 220, 220), 'audio': 'honk'},
    'penguin': {'template': 'bird', 'color': (20, 20, 20), 'audio': 'quack'},
    'ostrich': {'template': 'bird', 'color': (50, 50, 50), 'audio': 'grunt'},
    'flamingo': {'template': 'bird', 'color': (255, 105, 180), 'audio': 'honk'},
    'peacock': {'template': 'bird', 'color': (0, 128, 128), 'audio': 'caw'},
    'seagull': {'template': 'bird', 'color': (240, 240, 240), 'audio': 'caw'},
    'woodpecker': {'template': 'bird', 'color': (200, 50, 50), 'audio': 'chirp'},
    'turkey': {'template': 'bird', 'color': (139, 69, 19), 'audio': 'gobble'},
    'pelican': {'template': 'bird', 'color': (245, 245, 245), 'audio': 'grunt'},

    # Farm / Ungulates (Hooved / Wide snout)
    'cow': {'template': 'ungulate', 'color': (240, 240, 240), 'spots': True, 'audio': 'moo'},
    'pig': {'template': 'ungulate', 'color': (255, 182, 193), 'audio': 'oink'},
    'sheep': {'template': 'ungulate', 'color': (250, 250, 250), 'audio': 'baa'},
    'goat': {'template': 'ungulate', 'color': (211, 211, 211), 'audio': 'baa'},
    'horse': {'template': 'ungulate', 'color': (139, 69, 19), 'audio': 'neigh'},
    'donkey': {'template': 'ungulate', 'color': (169, 169, 169), 'audio': 'neigh'},
    'deer': {'template': 'ungulate', 'color': (160, 82, 45), 'audio': 'grunt'},
    'moose': {'template': 'ungulate', 'color': (101, 67, 33), 'audio': 'grunt'},
    'elk': {'template': 'ungulate', 'color': (184, 134, 11), 'audio': 'howl'},
    'camel': {'template': 'ungulate', 'color': (194, 178, 128), 'audio': 'grunt'},
    'llama': {'template': 'ungulate', 'color': (255, 250, 240), 'audio': 'grunt'},
    'alpaca': {'template': 'ungulate', 'color': (205, 180, 150), 'audio': 'grunt'},
    'zebra': {'template': 'ungulate', 'color': (240, 240, 240), 'stripes': True, 'audio': 'neigh'},
    'giraffe': {'template': 'ungulate', 'color': (255, 215, 0), 'spots': True, 'audio': 'grunt'},
    'hippo': {'template': 'ungulate', 'color': (119, 136, 153), 'audio': 'roar'},
    'rhino': {'template': 'ungulate', 'color': (128, 128, 128), 'audio': 'roar'},
    'elephant': {'template': 'ungulate', 'color': (169, 169, 169), 'trunk': True, 'audio': 'trumpet'},
    'bull': {'template': 'ungulate', 'color': (60, 40, 20), 'audio': 'moo'},
    'buffalo': {'template': 'ungulate', 'color': (90, 60, 40), 'audio': 'moo'},

    # Rodents / Small mammals
    'mouse': {'template': 'rodent', 'color': (200, 200, 200), 'audio': 'squeak'},
    'rat': {'template': 'rodent', 'color': (150, 150, 150), 'audio': 'squeak'},
    'squirrel': {'template': 'rodent', 'color': (139, 69, 19), 'audio': 'squeak'},
    'rabbit': {'template': 'rodent', 'color': (240, 240, 240), 'long_ears': True, 'audio': 'squeak'},
    'bunny': {'template': 'rodent', 'color': (255, 255, 255), 'long_ears': True, 'audio': 'squeak'},
    'hamster': {'template': 'rodent', 'color': (210, 180, 140), 'audio': 'squeak'},
    'guinea pig': {'template': 'rodent', 'color': (205, 133, 63), 'audio': 'squeak'},
    'beaver': {'template': 'rodent', 'color': (160, 82, 45), 'audio': 'grunt'},
    'chipmunk': {'template': 'rodent', 'color': (222, 184, 135), 'audio': 'squeak'},
    'porcupine': {'template': 'rodent', 'color': (105, 105, 105), 'audio': 'grunt'},
    'hedgehog': {'template': 'rodent', 'color': (139, 115, 85), 'audio': 'squeak'},
    'badger': {'template': 'rodent', 'color': (50, 50, 50), 'audio': 'grunt'},
    'skunk': {'template': 'rodent', 'color': (20, 20, 20), 'audio': 'squeak'},
    'raccoon': {'template': 'rodent', 'color': (120, 120, 120), 'audio': 'squeak'},
    'ferret': {'template': 'rodent', 'color': (210, 180, 140), 'audio': 'squeak'},

    # Reptiles & Amphibians
    'snake': {'template': 'reptile', 'color': (34, 139, 34), 'audio': 'hiss'},
    'lizard': {'template': 'reptile', 'color': (50, 205, 50), 'audio': 'hiss'},
    'turtle': {'template': 'reptile', 'color': (0, 100, 0), 'audio': 'hiss'},
    'crocodile': {'template': 'reptile', 'color': (85, 107, 47), 'audio': 'roar'},
    'alligator': {'template': 'reptile', 'color': (72, 99, 45), 'audio': 'roar'},
    'frog': {'template': 'reptile', 'color': (124, 252, 0), 'audio': 'croak'},
    'toad': {'template': 'reptile', 'color': (143, 188, 143), 'audio': 'croak'},
    'salamander': {'template': 'reptile', 'color': (255, 69, 0), 'audio': 'hiss'},
    'chameleon': {'template': 'reptile', 'color': (173, 255, 47), 'audio': 'hiss'},
    'iguana': {'template': 'reptile', 'color': (107, 142, 35), 'audio': 'hiss'},
    'gecko': {'template': 'reptile', 'color': (152, 251, 152), 'audio': 'chirp'},

    # Bears & Primates
    'bear': {'template': 'bear', 'color': (139, 69, 19), 'audio': 'roar'},
    'panda': {'template': 'bear', 'color': (245, 245, 245), 'panda_eyes': True, 'audio': 'grunt'},
    'grizzly': {'template': 'bear', 'color': (101, 67, 33), 'audio': 'roar'},
    'polar bear': {'template': 'bear', 'color': (255, 250, 250), 'audio': 'roar'},
    'koala': {'template': 'bear', 'color': (169, 169, 169), 'audio': 'grunt'},
    'sloth': {'template': 'bear', 'color': (188, 143, 143), 'audio': 'grunt'},
    'monkey': {'template': 'bear', 'color': (160, 82, 45), 'audio': 'hoot'},
    'gorilla': {'template': 'bear', 'color': (40, 40, 40), 'audio': 'roar'},
    'chimp': {'template': 'bear', 'color': (50, 50, 50), 'audio': 'hoot'},
    'orangutan': {'template': 'bear', 'color': (210, 105, 30), 'audio': 'hoot'},
    'baboon': {'template': 'bear', 'color': (112, 128, 144), 'audio': 'grunt'},
    'lemur': {'template': 'bear', 'color': (200, 200, 200), 'audio': 'squeak'},

    # Aquatic
    'fish': {'template': 'aquatic', 'color': (255, 140, 0), 'audio': 'bubble'},
    'shark': {'template': 'aquatic', 'color': (119, 136, 153), 'audio': 'bubble'},
    'whale': {'template': 'aquatic', 'color': (70, 130, 180), 'audio': 'howl'},
    'dolphin': {'template': 'aquatic', 'color': (176, 196, 222), 'audio': 'squeak'},
    'octopus': {'template': 'aquatic', 'color': (128, 0, 128), 'audio': 'bubble'},
    'squid': {'template': 'aquatic', 'color': (255, 105, 180), 'audio': 'bubble'},
    'crab': {'template': 'aquatic', 'color': (220, 20, 60), 'audio': 'bubble'},
    'lobster': {'template': 'aquatic', 'color': (178, 34, 34), 'audio': 'bubble'},
    'seahorse': {'template': 'aquatic', 'color': (255, 215, 0), 'audio': 'bubble'},
    'starfish': {'template': 'aquatic', 'color': (255, 127, 80), 'audio': 'bubble'},
    'seal': {'template': 'aquatic', 'color': (192, 192, 192), 'audio': 'bark'},
    'walrus': {'template': 'aquatic', 'color': (139, 115, 85), 'audio': 'grunt'},
    'otter': {'template': 'aquatic', 'color': (160, 82, 45), 'audio': 'squeak'},
    'manatee': {'template': 'aquatic', 'color': (169, 169, 169), 'audio': 'bubble'},
}
